import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import type { Organization, Submission, SubmissionField } from "@/lib/templates/types";

interface Props {
  org: Organization;
  submission: Submission & { fields: SubmissionField[] };
}

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", backgroundColor: "#ffffff" },
  header: { marginBottom: 24, borderBottom: "1px solid #e4e4e7", paddingBottom: 16 },
  orgName: { fontSize: 18, fontWeight: "bold", color: "#18181b" },
  title: { fontSize: 12, color: "#71717a", marginTop: 4 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 11, fontWeight: "bold", color: "#18181b", marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 },
  row: { flexDirection: "row", marginBottom: 6 },
  label: { fontSize: 9, color: "#71717a", width: 140 },
  value: { fontSize: 9, color: "#18181b", flex: 1 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#a1a1aa" },
});

export function TaxFormDocument({ org, submission }: Props) {
  const getField = (key: string) =>
    submission.fields.find((f) => f.field_key === key)?.field_value ?? "—";

  const personalFields: [string, string][] = [
    ["First Name", getField("firstName")],
    ["Last Name", getField("lastName")],
    ["Date of Birth", getField("dob")],
    ["Address", getField("address")],
    ["City", getField("city")],
    ["State", getField("state")],
    ["ZIP", getField("zip")],
    ["Email", getField("email")],
    ["Phone", getField("phone")],
    ["Filing Status", getField("filingStatus")],
  ];

  const incomeFields: [string, string][] = [
    ["Employer Name", getField("employerName")],
    ["Employer EIN", getField("employerEin")],
    ["Wages (Box 1)", getField("wagesBox1")],
    ["Federal Tax Withheld (Box 2)", getField("federalTaxBox2")],
    ["Social Security Tax (Box 4)", getField("socialSecurityBox4")],
    ["Medicare Tax (Box 6)", getField("medicareBox6")],
  ];

  const deductionFields: [string, string][] = [
    ["Deduction Type", getField("deductionType")],
    ["Mortgage Interest", getField("mortgageInterest")],
    ["Charitable Contributions", getField("charitableContributions")],
    ["Student Loan Interest", getField("studentLoanInterest")],
    ["Qualifying Children", getField("childTaxCredit")],
  ];

  const sections: [string, [string, string][]][] = [
    ["Personal Information", personalFields],
    ["Income", incomeFields],
    ["Deductions & Credits", deductionFields],
  ];

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.orgName}>{org.name}</Text>
          <Text style={styles.title}>
            Tax Preparation Intake, Submitted{" "}
            {new Date(
              submission.submitted_at ?? submission.created_at
            ).toLocaleDateString()}
          </Text>
        </View>
        {sections.map(([title, fields]) => (
          <View key={title} style={styles.section}>
            <Text style={styles.sectionTitle}>{title}</Text>
            {fields.map(([label, value]) => (
              <View key={label} style={styles.row}>
                <Text style={styles.label}>{label}</Text>
                <Text style={styles.value}>{value}</Text>
              </View>
            ))}
          </View>
        ))}
        <Text style={styles.footer}>Generated by FormFlow · {org.name}</Text>
      </Page>
    </Document>
  );
}
